import { Box, Heading, Text } from '@chakra-ui/react'
import type { NextPage } from "next";
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'


const Templates: NextPage = () => {
    return (
        <>
            <Head>
                <title>PPBL Summer 2022</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Box m='5' p='5'>
                <Heading>Templates for each rendering method in Next.js</Heading>
                <Text p='3' color='purple.700'>
                    <Link href="/templates/isr">ISR</Link>
                </Text>
                <Text p='3' color='purple.700'>
                    <Link href="/templates/ssg">SSG</Link>
                </Text>
                <Text p='3' color='purple.700'>
                    <Link href="/templates/ssr">SSR</Link>
                </Text>
                <Text p='3' color='purple.700'>
                    <Link href="/templates/csr">Client Side</Link>
                </Text>
            </Box>
        </>
    )
}

export default Templates